#!/bin/sh

jupyter nbextension enable codefolding/main
jupyter nbextension enable codefolding/edit
jupyter nbextension enable varInspector/main
jupyter nbextension enable toc2/main
jupyter nbextension enable collapsible_headings/main
